#!/bin/sh

# Set the desktop background color
xsetroot -solid '#000000' &

# Startup volume
pactl set-sink-volume 0 '100%' &

# Disable beeps
xset -b &

# Keyboard layout setting
setxkbmap -layout br -option grp:alt_shift_toggle &

# DPMS monitor setting (standby -> suspend -> off) (seconds)
#xset dpms 300 600 900 &
xset -dpms; xset s off; xset s blank

# Set LCD brightness
#xbacklight -set 100 &
echo 852 > /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness

# Set Background
feh --bg-fill /home/rdini/Pictures/stevenUniverse/thumb-1920-735768.png &

# Screensaver
#xscreensaver &
